-- Typed models for the Hypixel SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Guild

---@class GuildLoadMatch

---@class Housing
---@field houses? table
---@field success? boolean

---@class HousingLoadMatch
---@field houses? table
---@field success? boolean

---@class HousingListMatch
---@field houses? table
---@field success? boolean

---@class Other
---@field boosterState? table
---@field boosters? table
---@field staff_rollingDaily? number
---@field staff_total? number
---@field success? boolean
---@field watchdog_lastMinute? number
---@field watchdog_rollingDaily? number
---@field watchdog_total? number

---@class OtherLoadMatch
---@field boosterState? table
---@field boosters? table
---@field staff_rollingDaily? number
---@field staff_total? number
---@field success? boolean
---@field watchdog_lastMinute? number
---@field watchdog_rollingDaily? number
---@field watchdog_total? number

---@class OtherListMatch
---@field boosterState? table
---@field boosters? table
---@field staff_rollingDaily? number
---@field staff_total? number
---@field success? boolean
---@field watchdog_lastMinute? number
---@field watchdog_rollingDaily? number
---@field watchdog_total? number

---@class Player
---@field displayname? string
---@field firstLogin? number
---@field lastLogin? number
---@field lastLogout? number
---@field monthlyPackageRank? string
---@field newPackageRank? string
---@field packageRank? string
---@field rank? string
---@field stats? table
---@field uuid? string

---@class PlayerLoadMatch
---@field displayname? string
---@field firstLogin? number
---@field lastLogin? number
---@field lastLogout? number
---@field monthlyPackageRank? string
---@field newPackageRank? string
---@field packageRank? string
---@field rank? string
---@field stats? table
---@field uuid? string

---@class PlayerData
---@field date? number
---@field ended? number
---@field gameType? string
---@field map? string
---@field mode? string
---@field online? boolean

---@class PlayerDataLoadMatch
---@field date? number
---@field ended? number
---@field gameType? string
---@field map? string
---@field mode? string
---@field online? boolean

---@class PlayerDataListMatch
---@field date? number
---@field ended? number
---@field gameType? string
---@field map? string
---@field mode? string
---@field online? boolean

---@class Resource
---@field databaseName? string
---@field id? number
---@field lastUpdated? number
---@field modeNames? table
---@field name? string
---@field one_time? table
---@field rarities? table
---@field success? boolean
---@field tiered? table
---@field types? table

---@class ResourceLoadMatch
---@field databaseName? string
---@field id number
---@field lastUpdated? number
---@field modeNames? table
---@field name? string
---@field one_time? table
---@field rarities? table
---@field success? boolean
---@field tiered? table
---@field types? table

---@class SkyBlock
---@field auctioneer? string
---@field auctions? table
---@field bids? table
---@field category? string
---@field claimed? boolean
---@field claimed_bidders? table
---@field color? string
---@field coop? table
---@field current? table
---@field end? number
---@field events? table
---@field extra? string
---@field fullLore? table
---@field highest_bid_amount? number
---@field id? string
---@field item? table
---@field item_bytes? table
---@field item_lore? string
---@field item_name? string
---@field lastUpdated? number
---@field link? string
---@field lore? string
---@field material? string
---@field mayor? table
---@field name? string
---@field npc_sell_price? number
---@field page? number
---@field profile_id? string
---@field profiles? table
---@field progress? number
---@field requiredAmount? number
---@field sales? table
---@field start? number
---@field starting_bid? number
---@field stats? table
---@field success? boolean
---@field text? string
---@field tier? string
---@field tiers? table
---@field title? string
---@field totalAuctions? number
---@field totalPages? number
---@field uuid? string

---@class SkyBlockLoadMatch
---@field auctioneer? string
---@field auctions? table
---@field bids? table
---@field category? string
---@field claimed? boolean
---@field claimed_bidders? table
---@field color? string
---@field coop? table
---@field current? table
---@field end? number
---@field events? table
---@field extra? string
---@field fullLore? table
---@field highest_bid_amount? number
---@field id string
---@field item? table
---@field item_bytes? table
---@field item_lore? string
---@field item_name? string
---@field lastUpdated? number
---@field link? string
---@field lore? string
---@field material? string
---@field mayor? table
---@field name? string
---@field npc_sell_price? number
---@field page? number
---@field profile_id? string
---@field profiles? table
---@field progress? number
---@field requiredAmount? number
---@field sales? table
---@field start? number
---@field starting_bid? number
---@field stats? table
---@field success? boolean
---@field text? string
---@field tier? string
---@field tiers? table
---@field title? string
---@field totalAuctions? number
---@field totalPages? number
---@field uuid? string

---@class SkyBlockListMatch
---@field auctioneer? string
---@field auctions? table
---@field bids? table
---@field category? string
---@field claimed? boolean
---@field claimed_bidders? table
---@field color? string
---@field coop? table
---@field current? table
---@field end? number
---@field events? table
---@field extra? string
---@field fullLore? table
---@field highest_bid_amount? number
---@field id? string
---@field item? table
---@field item_bytes? table
---@field item_lore? string
---@field item_name? string
---@field lastUpdated? number
---@field link? string
---@field lore? string
---@field material? string
---@field mayor? table
---@field name? string
---@field npc_sell_price? number
---@field page? number
---@field profile_id? string
---@field profiles? table
---@field progress? number
---@field requiredAmount? number
---@field sales? table
---@field start? number
---@field starting_bid? number
---@field stats? table
---@field success? boolean
---@field text? string
---@field tier? string
---@field tiers? table
---@field title? string
---@field totalAuctions? number
---@field totalPages? number
---@field uuid? string

local M = {}

return M
